use_frameworks!


source 'https://github.com/iOSModularization/AHFMSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'



target 'AHFMCategoryVCServices_Example' do
  pod 'AHFMCategoryVCServices', :path => '../'

  target 'AHFMCategoryVCServices_Tests' do
    inherit! :search_paths

    
  end
end
